v0:
  socket:
    autoprune: true
  clipboard:
    if: true
    backend: default
  commands:
    browser:
      if: true
      command: "!$BROWSER"
  9p:
    default:
      if: true
      location: '!printf "%%s/.local/share/remote-files" "$HOME"'
